### ISSUE TITLE
Настройка описание запросов для тестов SmartItemController через файл

### ISSUE THREAD

**Issue by ZhukovAM** [pqdn/Cephei#30]

**Comment by pqdn** [comment]
Что ты имеешь в виду, если по русски?

**Comment by ZhukovAM** [comment]
Если кратко, то так как у нас есть несколько видов сущностей, которые мы ожидаем, то и запросы для каждой сущности разные. и описание этих запросов хочу описывать в файле. Чтобы тупо составляем список запросов и они все проверяются.
